# Generated by Django 3.0.2 on 2020-01-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ez_important', models.BooleanField(default=False)),
                ('ez_urgent', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('time_create', models.BigIntegerField(default=0)),
                ('time_update', models.BigIntegerField(default=0)),
                ('short_description', models.CharField(max_length=1000)),
                ('long_description', models.CharField(max_length=2500)),
            ],
        ),
    ]
